### ISSUE TITLE
GPLv3 and MIT license compatibility

### ISSUE THREAD

**Issue by bbvch13531** [ryuhangyeong/daily-health-originer#11]
## Type
-Doc

## Description
- This repo uses [MongoDB](https://www.mongodb.com/community/licensing) that follows GNG AGPLv3.0 license.
daily-health-originer should not follows MIT license because MIT is not compatible to GNG AGPLv3.0. Please check your license compatibility please.

**Comment by ryuhangyeong** [comment]
@bbvch13531  Thank you for your feedback. However, I can not change it immediately. We will change the license later. Thank you for your interest.

**Comment by ryuhangyeong** [comment]
@bbvch13531  Thank you for your interest.
